# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app}}
  namespace: {{.Values.metadata.namespace}}
  labels:
    app: {{.Values.app}}
spec:
  ports:
  - port: {{.Values.service.port}}
    targetPort: {{.Values.service.targetPort}}
    protocol: TCP
  selector:
    app: {{.Values.app}}
  type: {{.Values.service.type}}